on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

# https://github.com/OWNER/REPO/settings/actions
# MUST CHANGE GITHUB_TOKEN PERMISSION FROM READ TO WRITE
# MUST CHANGE GITHUB_TOKEN PERMISSION ALLOW PULL REQUESTS
# ⚠ ⚠ ⚠ You need merge pull request manually ⚠ ⚠ ⚠
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - run: xvfb-run -a yarn test
        if: runner.os == 'Linux'
      - run: yarn test
        if: runner.os != 'Linux'

      # Release please create a pull request to the 'master' branch
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          #package-name: release-please-action
          extra-files: |
            README.md
            CHANGELOG.md

